### ISSUE TITLE
How can I save the downloads into SD card

### ISSUE THREAD

**Issue by ashokkumar88** [kaikcreator/downgularJS#1]
Hi,

How Can I save the downloads into SD Card. Please help.

**Comment by kaikcreator** [comment]
When you use method **downgularJSQueue.build** you can define a folder from the root location provided by **windows.requestFileSystem**.

>var myQueue = downgularQueue.build('nameOfTheQueue', **'folder/to/downloads'**, callbackOnDownload);

However, root location of file downloads **depends on** [**Phonegap File Plugin API**](http://docs.phonegap.com/en/edge/cordova_file_file.md.html#requestFileSystem). Here you have some hints about [file system layout depending on the OS.](http://ngcordova.com/docs/plugins/file/)

**Comment by ashokkumar88** [comment]
Thanks for your reply. But the 'folder/to/downloads' is created under the application root. How Can I change the root location in the Phonegap File Plugin API?

**Comment by kaikcreator** [comment]
I don't know if you can specify some folder to the requestFileSystem call. I invite you to explore it! Here you might find some more info: check section [Where to Store Files](https://github.com/apache/cordova-plugin-file) 

Cheers!

**Comment by ashokkumar88** [comment]
I successfully saved the downloads to sdcard. But is there any method i can see the download progress percentage? Thanks

**Comment by kaikcreator** [comment]
There's no method like that, right now.

**Comment by kaikcreator** [comment]
I'll close this thread, since this is not an issue but a nice to be feature in the future ;)
